config/routes.rb
Rails.application.routes.draw do
  get 'books' => "books#index"
  post "books" => "books#create"
  get 'books/:id' => "books#show", as: "book"
  get 'books/:id/edit' => "books#edit", as: "edit_book"
  root :to => 'homes#top'
  patch "books/:id" => "books#update", as: "update_book"
  delete "books/:id" => "books#destroy", as: "destroy_book"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   def index
      @books = Book.all
      @book = Book.new
   end

    def create
      @book = Book.new(book_params)

        if @book.save
          flash[:success] = "Book was successfully created."
          redirect_to book_path(@book.id)

        else
          @books = Book.all
          render :index

        end
    end

    def show
      @book = Book.find(params[:id])

    end

    def edit
      @book = Book.find(params[:id])

    end

    def update
      @book = Book.find(params[:id])
        if @book.update(book_params)

          flash[:success] = "Book was successfully updated."
          redirect_to book_path(@book.id)
        else
          render :edit
        end
    end

    def destroy
      @book = Book.find(params[:id])
      if @book.destroy
        flash[:success] = "Book was successfully destroyed."
        redirect_to "/books"
      else
        @books = Book.all
        render :index
      end
    end

    private

    def book_params
      params.require(:book).permit(:title,:body)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch, local:true do |n| %>

  <p>Title</p>
  <%= n.text_field :title %>

  <p>Body</p>
  <%= n.text_area :body %>

  <p><%= n.submit "Update Book" %></p>

  <p><%= link_to "Show", book_path(@book.id) %><%= " |" %>
  <%= link_to "Back", "/books" %></p>

<% end %>

app/views/books/index.html.erb
<%= flash[:success] %>

<h1>Books</h1>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>body</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show", book_path(book.id) %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
    </tr>
    <% end %>


  </table>

<h2>New book</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url:"/books", method: :post, local:true do |n| %>

  <p>Title</p>
  <%= n.text_field :title %>

  <p>Body</p>
  <%= n.text_area :body %>

  <p><%= n.submit "Create Book" %></p>

<% end %>

app/views/books/show.html.erb
<%= flash[:success] %>

<p>Title:<%= @book.title %></p>
<p>Body:<%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", "/books" %>

app/views/homes/top.html.erb
<h1 class="top-title">ようこそ <strong>Bookers</strong>へ！</h1>
<p class="top-main">
  <strong>
    Bookers
  </strong>
    では、さまざまな書籍に関するあなたの意見や
</p>

<p class="top-main">
  印象を共有し交換することができます
</p>

<a href="/books">START</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>